_target_: src.identification.model.new_module.IdentificationModel

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler: null

net:
  _target_: src.identification.model.net.new_transformer.TransformerSeq2Seq
  _partial_: true
  # encoder_input_dim
  d_model: 256
  encoder_n_heads: 4
  encoder_n_layers: 2
  encoder_dim_feedforward: 1024
  decoder_n_heads: 4
  decoder_n_layers: 2
  decoder_dim_feedforward: 1024
  dropout: 0.1

teacher_forcing_ratio: 1.0


