_target_: src.dataframe.dataframe.CSVDataFrameLoader

dataset_dir: ${paths.data_dir}/NOx/raw
names: ["boiler load", "total coal feed rate", "inlet NOx concentration", "NH3 injection flow",
       "None", "inlet flue gas temperature", "inlet flue gas flow", "inlet O2 content",
       "NOx emission concentration"]
sep: "\t"
drop_names: ["None"]
