_target_: src.datamodules.base.ImputeDataModule

n_steps: 20
n_strides: 1
#train_ratio: Optional[float]=0.8, 
#val_ratio: Optional[float]=0.1, 
#test_ratio: Optional[float]=0.1, 
batch_size: 32
num_workers: 0 

