_target_: src.datamodules.base.ForecastDataModule 

target: "NOx emission concentration"
forecast_horizon: 1 
context_length: 32
is_timestamp_indexed: False
train_ratio: 0.7
val_ratio: 0.1 
test_ratio: 0.2
batch_size: 32 
num_workers: 0 
